services:
  - type: web
    name: deployment-assignment
    runtime: node
    buildCommand: npm install && pip install -r requirements.txt && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY
        sync: false
      - key: NODE_VERSION
        value: 20
